apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stream-forge-web
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      serviceAccountName: stream-forge-web
      containers:
        - image: gcr.io/PROJECT_ID/stream-forge-web:latest
          ports:
            - containerPort: 80
